FROM nginx:latest

RUN apt-get update \
    && apt-get install -y \
        nodejs \
        npm \
    && npm install -g uglify-js uglifycss

COPY estilos.css /app/estilos.css
COPY script.js /app/script.js

RUN uglifycss /app/estilos.css > /usr/share/nginx/html/estilos.css
RUN uglifyjs /app/script.js -o /usr/share/nginx/html/script.js

COPY index.html /usr/share/nginx/html/index.html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
